FROM node:alpine AS build
RUN mkdir /app
WORKDIR /app/
COPY ./../ ./
RUN npm i
RUN npm run build
FROM node:alpine
WORKDIR /app/
COPY --from=build /app/build /app/build
EXPOSE 80
RUN npm i serve
#ENV HTTPS=true
CMD npx serve -p 80 -s build

