FROM node:alpine AS build
RUN mkdir /app
WORKDIR /app/
COPY ./../ ./
RUN npm i
RUN npm run build
FROM node:alpine
WORKDIR /app/
COPY --from=build /app/build /app/build
COPY --from=build /app/src/certs/cert-vault-fp-ofcourse-secure42cd9f29-8da8-4a3f-8ed7-5d88730eaf38-20231117.pfx /app/certs
EXPOSE 443
RUN npm i serve
CMD npx serve -p 443 -s build --ssl-cert ./certs/cert-vault-fp-ofcourse-secure42cd9f29-8da8-4a3f-8ed7-5d88730eaf38-20231117.pfx
