version: '3.8'
services:
  user-api:
    ports:
      - "8080:8080"
    build:
      context: ./FPBESpringBoot/
      dockerfile: Dockerfile
    image: psdemoacrangelo.azurecr.io/fpbe:latest
  front-end:
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: psdemoacrangelo.azurecr.io/fpfe:latest
  micro-services-pg2mongo:
    image: psdemoacrangelo.azurecr.io/micro-services-pg2mong:latest
    build:
      context: ./micro-services-pg2mongo
      dockerfile: Dockerfile
  courseapi:
   ports:
      - "8081:8081"
   build:
    dockerfile: Dockerfile
    context: ./courseapi
   image: psdemoacrangelo.azurecr.io/courseapi:latest
  kafka:
   ports:
     - "9092:9092"
   build:
     context: ./kafka/
     dockerfile: Dockerfile
   image: psdemoacrangelo.azurecr.io/kafka:latest

  #nginx-proxy:
  # image: psdemoacrangelo.azurecr.io/nginx:latest
  # build:
  #  context: ./nginx/
  #  dockerfile: Dockerfile
  # ports:
  #  - "80:80"
  #  - "443:443"
 #  volumes:
 #   - WEBAPP_STORAGE_HOME:/etc/nginx/conf.d
  # depends_on:
  #  - user-api
  #  - front-end
  #  - micro-services-pg2mongo
  #  - courseapi
#volumes:
#  WEBAPP_STORAGE_HOME:
