version: '3.8'
services:
  user-api:
    ports:
      - "8080:8080"
    build:
      context: ./FPBESpringBoot/
      dockerfile: Dockerfile
    image: $AZURE_REGISTRY_SERVER/fpbe:latest
  front-end:
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: dockerfile
    image: $AZURE_REGISTRY_SERVER/fpfe:latest
  micro-services-pg2mongo:
    image: $AZURE_REGISTRY_SERVER/micro-services-pg2mong:latest
    build:
      context: ./micro-services-pg2mongo
      dockerfile: Dockerfile
  courseapi:
   ports:
      - "80:8081"
   build:
    dockerfile: Dockerfile
    context: ./courseapi
   image: $AZURE_REGISTRY_SERVER/courseapi:latest
  
