version: 3.1
services:
  user-api:
    environment:
     - URL
     - USERNAME
     - PSWD
    build:
      args:
       - URL=URL
       - USERNAME=USERNAME
       - PSWD=PSWD
      context: ./FPBESpringBoot/
      dockerfile: Dockerfile
    image: $AZURE_REGISTRY_SERVER/fpbe:latest
  front-end:
      build:
       context: ./frontend
       dockerfile: dockerfile
      image: $AZURE_REGISTRY_SERVER/fpfe:latest
  micro-services-pg2mongo:
   image: $AZURE_REGISTRY_SERVER/micro-services-pg2mong:latest
   environment:
    - PGQL_HOST
    - PGQL_PORT
    - PGQL_USERNAME
    - PGQL_PASSWORD
    - PGQL_DATABASE
    - MG_URL
   build:
    args:
      - PGQL_HOST
      - PGQL_PORT
      - PGQL_USERNAME
      - PGQL_PASSWORD
      - PGQL_DATABASE
      - MG_URL
    context: ./micro-services-pg2mongo
    dockerfile: Dockerfile
  courseapi:
   environment:
    - MG_URL
   build:
    dockerfile: Dockerfile
    context: ./courseapi
    args:
      - MG_URL=$MG_URL
   image: $AZURE_REGISTRY_SERVER/courseapi:latest
  




