apiVersion: v1
kind: Secret
metadata:
 name: acr-secret
type: Opaque
data: 
 docker-server: cHNkZW1vYWNyYW5nZWxvLmF6dXJlY3IuaW8=
 docker-username: cHNkZW1vYWNyYW5nZWxv
 docker-password: VTBvNk5rdit2Yzd3ZUVLUk55bXJ4Mjg2ZjZEc3VZWlFUZy93TG04Q3R2K0FDUkNrbGtTSg==
---
apiVersion: v1
kind: Secret
metadata:
 name: postgresql-params
type: Opaque
data:
 jdbc_url: amRiYzpwb3N0Z3Jlc3FsOi8vZnBiZXBncWwucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29tOjU0MzIvY3N0 
 host: ZnBiZXBncWwucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t
 port: NTQzMg==
 username: QW5nZWxv
 password: QmVsbGE1MTQh
 database: Y3N0
---
apiVersion: v1
kind: Secret
metadata:
 name: mongo-params
type: Opaque
data:
 url: bW9uZ29kYjovL2RvY2RiZnA6T2xzNXlFNUdxdm4waWt5emNSa2NjQWE4SEM3Z3E4QVNObTMyOXNkcHVhSktFbDE1cnV1eFYyNmZqNEgzQlZhbGM0VGZPeE83V3pTR0FDRGJ0QnUxaUE9PUBkb2NkYmZwLm1vbmdvLmNvc21vcy5henVyZS5jb206MTAyNTUvP3NzbD10cnVlJnJlcGxpY2FTZXQ9Z2xvYmFsZGImcmV0cnl3cml0ZXM9ZmFsc2UmbWF4SWRsZVRpbWVNUz0xMjAwMDAmYXBwTmFtZT1AZG9jZGJmcEA=
