apiVersion: v1
kind: Secret
metadata:
 name: acr-secret
type: Opaque
data: 
 docker-server: cHNkZW1vYWNyYW5nbGVvLmF6dXJlY3IuaW8=
 docker-username: cHNkZW1vYWNyYW5nbGVv
 docker-password: VTBvNk5rdit2Yzd3ZUVLUk55bXJ4Mjg2ZjZEc3VZWlFUZy93TG04Q3R2K0FDUkNrbGtTSg==
