apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
 labels:
  app: frontend
spec:
 replicas: 2
 selector:
  matchLabels:
   app: frontend
 template:
  metadata:
    labels:
      app: frontend
  spec:
    containers:
    - name: frontend
      image: psdemoacrangelo.azurecr.io/fpfe:latest
      ports:
      - containerPort: 80
     # env:
     # - name: docker-server
     #   valueFrom: 
     #    secretKeyRef:
     #      name: acr-secret
     #      key: docker-server
     # - name: docker-password
     #   valueFrom: 
     #    secretKeyRef:
     #      name: acr-secret
     #      key: docker-password
     # - name: docker-username
     #   valueFrom: 
     #    secretKeyRef:
     #      name: acr-secret
     #      key: docker-username
    imagePullSecrets:
    - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
 name: frontend-service
spec:
 type: NodePort
 selector:
   app: frontend
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 30000