apiVersion: apps/v1
kind: Deployment
metadata:
 name: webapp-deployment
 labels:
  app: webapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: webapp
 template:
  metadata:
    labels:
      app: webapp
  spec:
    containers:
    - name: frontend
      image: psdemoacrangelo.azurecr.io/fpfe:latest
      ports:
      - containerPort: 80
        protocol: TCP
        name: http

    - name: course-api
      image: psdemoacrangelo.azurecr.io/courseapi:latest
      env:
      - name: MG_URL
        valueFrom:
          secretKeyRef:
            name: mongo-params
            key: url
      ports:
      - containerPort: 8081

    - name: user-api
      image: psdemoacrangelo.azurecr.io/fpbe:latest
      env:
      - name: URL
        valueFrom:
         secretKeyRef:
          name: postgresql-params
          key: jdbc_url
      - name: USERNAME
        valueFrom:
         secretKeyRef:
          name: postgresql-params
          key: username
      - name: PSWD
        valueFrom:
         secretKeyRef:
          name: postgresql-params
          key: password
      ports:
      - containerPort: 8080
    - name: micro-services-pg2mongo
      image: psdemoacrangelo.azurecr.io/micro-services-pg2mong:latest
      env:
      - name: MG_URL
        valueFrom:
          secretKeyRef:
            name: mongo-params
            key: url
      - name: PGQL_HOST
        valueFrom:
          secretKeyRef:
            name: postgresql-params
            key: host
      - name: PGQL_PORT
        valueFrom:
          secretKeyRef:
            name: postgresql-params
            key: port
      - name: PGQL_USERNAME
        valueFrom:
          secretKeyRef:
            name: postgresql-params
            key: username
      - name: PGQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgresql-params
            key: password
      - name: PGQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: postgresql-params
            key: database
      
    imagePullSecrets:
    - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
 name: webapp-service
 #annotations:
 # service.beta.kubernetes.io/azure-load-balancer-ipv4: 20.33.12.51
 labels:
   app: webapp
   
spec:
 #type: LoadBalancer
 #loadBalancerIP: 20.121.73.181
 selector:
   app: webapp
 ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: 80
   - name: api-v1
     protocol: TCP
     port: 8080
     targetPort: 8080
   - name: api-v2
     protocol: TCP
     port: 8081
     targetPort: 8081