server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://fpbepgql.postgres.database.azure.com/cst
    username: Angelo
    password: Bella514!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  web-application-type: servlet
    
