name: Deploy all moving parts of capstone
env:
  AZURE_WEBAPP_NAME: ${{ vars.AZURE_WEBAPP_NAME }}  # set this to the name of your Azure Web App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Setup docker-compose
        run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - name: Make docker-compose binaries executable
        run: sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Login to the ACR server
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_SERVER }}
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          
      - name: Build with docker compose
        env: 
          URL: ${{ secrets.DB_URL}}
          USERNAME: ${{ secrets.DB_USERNAME }}
          PSWD: ${{ secrets.DB_PSWD }}
          PGQL_HOST: ${{ secrets.PGQL_HOST }}
          PGQL_PORT: ${{ secrets.PGQL_PORT }}
          PGQL_USERNAME: ${{ secrets.PGQL_USERNAME }}
          PGQL_PASSWORD: ${{ secrets.PGQL_PASSWORD }}
          PGQL_DATABASE: ${{ secrets.PGQL_DATABASE }}
          MG_URL: ${{ secrets.MG_URL }}
          AZURE_REGISTRY_SERVER: ${{ secrets.AZURE_REGISTRY_SERVER }}
        run: |
         docker-compose build \
         --build-arg URL=$URL \
         --build-arg USERNAME=$USERNAME \
         --build-arg PSWD=$PSWD \
         --build-arg PGQL_HOST=$PGQL_HOST \
         --build-arg PGQL_PORT=$PGQL_PORT \
         --build-arg PGQL_USERNAME=$PGQL_USERNAME \
         --build-arg PGQL_PASSWORD=$PGQL_PASSWORD \
         --build-arg PGQL_DATABASE=$PGQL_DATABASE \
         --build-arg MG_URL=$MG_URL \
         --build-arg AZURE_REGISTRY_SERVER=$AZURE_REGISTRY_SERVER
        
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/courseapi:latest \
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/micro-services-pg2mong:latest \
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/fpbe:latest \
      - name: Push Docker image to ACR
        run: docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/fpfe:latest
        
      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/work/FinalProject/FinalProject/docker-compose.yml



  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: none

    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact


      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          configuration-file: docker-compose.yml
          images: |
           ${{ secrets.AZURE_REGISTRY_SERVER }}/courseapi:latest
           ${{ secrets.AZURE_REGISTRY_SERVER }}/micro-services-pg2mong:latest
           ${{ secrets.AZURE_REGISTRY_SERVER }}/fpbe:latest
           ${{ secrets.AZURE_REGISTRY_SERVER }}/fpfe:latest
          
           
